version: '3.8'

configs:
  HomeAssistantCoreConfig:
    name: HomeAssistantCoreConfig-4
    file: ./Configs/HomeAssistant/configs/configuration.yaml

  # HomeAssistantSecrets:
  #   name: HomeAssistantSecretsConfig-1
  #   file: ./Configs/HomeAssistant/secrets.yaml
  
volumes:
  homeassistantData:

services:
  HomeAssistant:
    image: homeassistant/home-assistant:stable
    configs:
      - source: HomeAssistantCoreConfig
        target: /config/configuration.yaml
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - homeassistantData:/config/.storage
    networks:
      - publicWeb