version: '3.8'

networks:
  publicWeb:
    name: publicWeb
    driver: overlay
    attachable: true

configs:
  WebConfig:
    name: WebConfig-2
    file: ./Configs/Web/Caddyfile.json

services:
  Web:
    image: kristianfoss/programs-caddy:caddy-cf-main-scratch
    command: ['run', '--config', '/etc/caddy/Caddyfile.json']
    configs:
      - source: WebConfig
        target: /etc/caddy/Caddyfile.json
        uid: '1000'
        gid: '1000'
        mode: 0440
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 12M
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    networks:
      - publicWeb
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress